modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mystical_nature"
version="1.0.0"
displayName="Mystical Nature"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Enter100, MCreator"

[[dependencies.mystical_nature]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




